import "./AssessmentHeader.css";
import Button from "./Button.jsx";
import useAssessmentActions from "../hooks/useAssessmentActions.js";

function AssessmentHeader({ assessment }) {
    const {
        generateAssessment,
        regenerateAssessment,
        generateDocument,
        publishAssessment,
        rollbackAssessment,
        deleteAssessment,
        addQuestion,
        parseAssessment,
        loading
    } = useAssessmentActions(assessment?.assessmentId);

    if (!assessment) {
        return null;
    }

    return (

        <div className="assessment-editor-header">

            <h1 className="assessment-editor-title">
                Assessment {assessment.assessmentNumber} : {assessment.chapterName}
            </h1>

            <p className="assessment-editor-subtitle">
                Manage assessment generation, editing, publishing and versioning.
            </p>

            <div className="assessment-editor-metadata">

                <div className="metadata-column">

                    <div className="metadata-item">
                        <strong>Assessment ID:</strong> {assessment.assessmentId}
                    </div>

                    <div className="metadata-item">
                        <strong>Version:</strong> {assessment.version ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Questions:</strong> {assessment.questionCount}
                    </div>

                    <div className="metadata-item">
                        <strong>Total Marks:</strong> {assessment.marks}
                    </div>

                    <div className="metadata-item">
                        <strong>Learning Outcomes:</strong> {assessment.learningOutcomeCount}
                    </div>

                </div>

                <div className="metadata-column">

                    <div className="metadata-item">
                        <strong>Generated On:</strong> {assessment.generatedOn ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Generated By:</strong> {assessment.generatedBy ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Updated On:</strong> {assessment.updatedOn ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Updated By:</strong> {assessment.updatedBy ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Status:</strong>

                        <span
                            className={`status-badge ${assessment.status
                                .toLowerCase()
                                .replace(/\s+/g, "-")}`}
                        >
                            {assessment.status}
                        </span>

                    </div>

                </div>

            </div>

            <div className="assessment-toolbar">

                <Button
                    text="Generate Assessment"
                    onClick={generateAssessment}
                    disabled={loading}
                />

                <Button
                    text="Regenerate Assessment"
                    onClick={regenerateAssessment}
                    disabled={loading}
                />

                <Button
                    text="Generate DOCX"
                    onClick={generateDocument}
                    disabled={loading}
                />

                <Button
                    text="Publish"
                    onClick={publishAssessment}
                    disabled={loading}
                />

                <Button
                    text="Rollback"
                    onClick={rollbackAssessment}
                    disabled={loading}
                />

                <Button
                    text="Delete Assessment"
                    onClick={deleteAssessment}
                    disabled={loading}
                />

                <Button
                    text="Add Question"
                    onClick={addQuestion}
                    disabled={loading}
                />

                <Button
                    text="Parse"
                    onClick={parseAssessment}
                    disabled={loading}
                />

            </div>

        </div>

    );

}

export default AssessmentHeader;
