import "./styles/AssessmentHeader.css";

import { useState } from "react";
import { useNavigate } from "react-router-dom";

import Button from "../Commons/Button.jsx";
import PromptDialog from "../Commons/PromptDialog.jsx";
import useAssessmentActions from "../../hooks/Assessment_Hooks/useAssessmentActions.js";

function AssessmentHeader({ assessment, chapterName, onRefresh, onDeleted }) {
    const navigate = useNavigate();

    const {
        regenerateAssessment,
        generateDocument,
        publishAssessment,
        rollbackAssessment,
        deleteAssessment,
        addQuestion,
        loading
    } = useAssessmentActions(assessment?.assessmentId);

    const [promptOpen, setPromptOpen] = useState(false);
    const [promptAction, setPromptAction] = useState(null);
    const [message, setMessage] = useState("");

    if (!assessment) {
        return null;
    }

    const runAction = async (label, action) => {
        console.log(`[AssessmentHeader] ${label} clicked for assessment:`, assessment.assessmentId);
        setMessage("");

        try {
            const response = await action();
            console.log(`[AssessmentHeader] ${label} response:`, response);

            if (response?.success === false) {
                setMessage(response.message || `${label} failed.`);
                return;
            }

            setMessage(response?.message || `${label} completed successfully.`);
            if (onRefresh) {
                await onRefresh();
            }
        } catch (error) {
            console.error(`[AssessmentHeader] ${label} failed:`, error);
            setMessage(`${label} failed.`);
        }
    };

    const openPrompt = (actionName) => {
        console.log("[AssessmentHeader] Opening prompt dialog for:", actionName);
        setPromptAction(actionName);
        setPromptOpen(true);
    };

    const handlePromptConfirm = async (prompt) => {
        setPromptOpen(false);

        if (promptAction === "regenerate") {
            await runAction("Regenerate Assessment", () => regenerateAssessment(prompt));
        }

        setPromptAction(null);
    };

    const handleDelete = async () => {
        const confirmed = window.confirm("Delete this assessment?");
        if (!confirmed) {
            console.log("[AssessmentHeader] Delete cancelled.");
            return;
        }

        const response = await deleteAssessment();
        console.log("[AssessmentHeader] Delete response:", response);

        if (response?.success === false) {
            setMessage(response.message || "Delete Assessment failed.");
            return;
        }

        setMessage(response?.message || "Assessment deleted successfully.");

        if (onDeleted) {
            onDeleted();
            return;
        }

        navigate("/");
    };

    const displayName = chapterName || assessment.chapterName || "";

    return (
        <div className="assessment-editor-header">

            <h1 className="assessment-editor-title">
                Assessment {assessment.assessmentNumber}
                {displayName ? ` : ${displayName}` : ""}
            </h1>

            <p className="assessment-editor-subtitle">
                Manage assessment generation, editing, publishing and versioning.
            </p>

            <div className="assessment-editor-metadata">

                <div className="metadata-column">

                    <div className="metadata-item">
                        <strong>Assessment ID:</strong> {assessment.assessmentId}
                    </div>

                    <div className="metadata-item">
                        <strong>Version:</strong> {assessment.version ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Questions:</strong> {assessment.numberOfQuestions ?? assessment.questionCount ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Total Marks:</strong> {assessment.marks}
                    </div>

                    <div className="metadata-item">
                        <strong>Learning Outcomes:</strong> {assessment.learningOutcomeCount ?? "-"}
                    </div>

                </div>

                <div className="metadata-column">

                    <div className="metadata-item">
                        <strong>Generated On:</strong> {assessment.generatedOn ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Generated By:</strong> {assessment.generatedBy ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Updated On:</strong> {assessment.updatedOn ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Updated By:</strong> {assessment.updatedBy ?? "-"}
                    </div>

                    <div className="metadata-item">
                        <strong>Status:</strong>

                        <span
                            className={`status-badge ${(assessment.status || "unknown")
                                .toLowerCase()
                                .replace(/\s+/g, "-")}`}
                        >
                            {assessment.status || "Unknown"}
                        </span>

                    </div>

                </div>

            </div>

            {
                message && (
                    <p className="assessment-editor-subtitle">
                        {message}
                    </p>
                )
            }

            <div className="assessment-toolbar">

                <Button
                    text="Regenerate Assessment"
                    onClick={() => openPrompt("regenerate")}
                    disabled={loading}
                />

                <Button
                    text="Generate DOCX"
                    onClick={() => runAction("Generate DOCX", generateDocument)}
                    disabled={loading}
                />

                <Button
                    text="Publish"
                    onClick={() => runAction("Publish", publishAssessment)}
                    disabled={loading}
                />

                <Button
                    text="Rollback"
                    onClick={() => runAction("Rollback", rollbackAssessment)}
                    disabled={loading}
                />

                <Button
                    text="Delete Assessment"
                    onClick={handleDelete}
                    disabled={loading}
                />

                <Button
                    text="Add Question"
                    onClick={() => runAction("Add Question", addQuestion)}
                    disabled={loading}
                />

            </div>

            <PromptDialog
                open={promptOpen}
                title="Regenerate Assessment"
                label="Optional regeneration prompt"
                confirmText="Regenerate"
                onClose={() => {
                    console.log("[AssessmentHeader] Prompt dialog closed.");
                    setPromptOpen(false);
                    setPromptAction(null);
                }}
                onConfirm={handlePromptConfirm}
            />

        </div>
    );
}

export default AssessmentHeader;
