"""Canonical constants used across services and controllers."""

SUCCESS = "SUCCESS"
FAILED = "FAILED"

DEFAULT_USER = "SYSTEM"

MAX_GENERATION_RETRIES = 3

ASSESSMENT_STATUS_GENERATED = "Generated"
ASSESSMENT_STATUS_PARSED = "Parsed"
ASSESSMENT_STATUS_PUBLISHED = "Published"
ASSESSMENT_STATUS_OUTDATED = "Outdated"
ASSESSMENT_STATUS_NOT_GENERATED = "Not Generated"

ASSESSMENT_STATUSES = {
    ASSESSMENT_STATUS_GENERATED,
    ASSESSMENT_STATUS_PARSED,
    ASSESSMENT_STATUS_PUBLISHED,
    ASSESSMENT_STATUS_OUTDATED,
    ASSESSMENT_STATUS_NOT_GENERATED,
}

QUESTION_TYPES = [
    "MCQ",
    "Short Answer",
    "Long Answer",
    "True / False",
    "Fill in the Blank",
]

DIFFICULTY_LEVELS = ["Easy", "Medium", "Hard"]

BLOOM_LEVELS = ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"]

DIFFICULTY_RATIOS = {
    "1-2": {"Easy": 0.40, "Medium": 0.50, "Hard": 0.10},
    "3-5": {"Easy": 0.30, "Medium": 0.60, "Hard": 0.10},
    "6-8": {"Easy": 0.20, "Medium": 0.60, "Hard": 0.20},
    "9-10": {"Easy": 0.15, "Medium": 0.60, "Hard": 0.25},
}

QUESTION_TYPE_RATIOS = {
    "MCQ": 0.30,
    "Short Answer": 0.25,
    "True / False": 0.15,
    "Fill in the Blank": 0.15,
    "Long Answer": 0.15,
}

BLOOM_MARKS = {
    "Remember": 1,
    "Understand": 1,
    "Apply": 2,
    "Analyze": 2,
    "Evaluate": 3,
    "Create": 3,
}

# Version log actions
ACTION_GENERATED = "GENERATED"
ACTION_REGENERATED = "REGENERATED"
ACTION_UPDATED = "UPDATED"
ACTION_DELETED = "DELETED"
ACTION_QUESTION_ADDED = "QUESTION_ADDED"
ACTION_QUESTION_UPDATED = "QUESTION_UPDATED"
ACTION_QUESTION_DELETED = "QUESTION_DELETED"
ACTION_QUESTION_REGENERATED = "QUESTION_REGENERATED"
ACTION_ANSWER_REGENERATED = "ANSWER_REGENERATED"
ACTION_ROLLED_BACK = "ROLLED_BACK"
ACTION_PUBLISHED = "PUBLISHED"
ACTION_PARSED = "PARSED"
ACTION_IMAGE_ADDED = "IMAGE_ADDED"
ACTION_IMAGE_DELETED = "IMAGE_DELETED"
ACTION_OUTCOMES_CHANGED = "OUTCOMES_CHANGED"
